### ISSUE TITLE
Support of GitHub Enterprise

### ISSUE THREAD

**Issue by slaweet** [vebr/jest-lcov-reporter#13]
I found this action and it looked pretty cool, so I tried to run it on a [GitHub Enterprise](https://github.com/enterprise) instance, but it failed because it tried to send the report to `api.github.com/...` instead of the URL which should be in `GITHUB_API_URL` - according to https://docs.github.com/en/actions/reference/environment-variables

```
Run vebr/jest-lcov-reporter@v0.2.0
RequestError [HttpError]: Bad credentials
    at /home/runner/_work/_actions/vebr/jest-lcov-reporter/v0.2.0/dist/main.js:6018:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async main$1 (/home/runner/_work/_actions/vebr/jest-lcov-reporter/v0.2.0/dist/main.js:22950:2) {
  name: 'HttpError',
  status: 401,
  headers: {
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset',
    connection: 'close',
    'content-length': '80',
    'content-security-policy': "default-src 'none'",
    'content-type': 'application/json; charset=utf-8',
    date: 'Tue, 02 Feb 2021 10:55:51 GMT',
    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
    server: 'GitHub.com',
    status: '401 Unauthorized',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    vary: 'Accept-Encoding, Accept, X-Requested-With',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'deny',
    'x-github-media-type': 'github.v3; format=json',
    'x-github-request-id': 'DB6E:35E5:47937F:C53B69:60192FB7',
    'x-ratelimit-limit': '60',
    'x-ratelimit-remaining': '59',
    'x-ratelimit-reset': '1612266951',
    'x-ratelimit-used': '1',
    'x-xss-protection': '1; mode=block'
  },
  request: {
    method: 'POST',
    url: 'api.github.com/repos/telltale/frontend/issues/589/comments',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit.js/16.35.0 Node.js/12.13.1 (Linux 4.19; x64)',
      authorization: 'token [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },
    body: `{"body":"Coverage after merging <b>speed-up-jest-tests</b> into <b>develop</b><table> [TABLE CoNTENT OMMITED for opening THIS GITHUB ISSUE]</table></details>"}`,
    request: { hook: [Function: bound bound register], validate: [Object] }
  },
  documentation_url: 'docs.github.com/rest'
}
Error: Bad credentials
```

**Comment by vebr** [comment]
Hello @slaweet , can u tell me more how to reproduce it? and have you double check the credentials is correct? 
Because I use  github [action](https://github.com/actions/toolkit/tree/master/packages/github) package to send the comment to repository, and i don't set any environment about `GITHUB_API_URL ` , Thanks.

**Comment by slaweet** [comment]
Hello @vebr, thank you for the response.

The relevant part of my workflow file is the following:
```yaml
---
name: Build
on:
  pull_request:
jobs:
  Test:
    runs-on: [ self-hosted ]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
      - run: yarn install
      - run: yarn test --coverage --runInBand --json --outputFile=result.json --testLocationInResults
      - uses: vebr/jest-lcov-reporter@v0.2.0
        if: always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: ./coverage/lcov.info
      - uses: tanmen/jest-reporter@v1
        if: always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
```

Though now that you mention that it works for you, I guess the difference is probably hidden behind `runs-on: [ self-hosted ]`, so it's probably not enough to reproduce and I have to dig deeper into our `self-hosted` runner setup.
