### ISSUE TITLE
Comment is updated even with option in false

### ISSUE THREAD

**Issue by ghost** [vebr/jest-lcov-reporter#21]
I have a workflow with two different jobs which each of them has this GA action.

```  
 - name: Publish code coverage report
    uses: vebr/jest-lcov-reporter@v0.2.1
     with:
        github-token: ${{ github.token }}
        name: Client Portal Coverage Report
        lcov-file: webapps/client-portal/coverage/lcov.info
        update-comment: false
```

```   
- name: Publish code coverage report
    uses: vebr/jest-lcov-reporter@v0.2.1
    with:
       github-token: ${{ github.token }}
       name: Qualifications Portal Coverage Report
        lcov-file: webapps/qualifications-portal/coverage/lcov.info
        update-comment: false
```

The issue is always there is only one comment created and it's being updated, so I never have the two comments.
