### ISSUE TITLE
update-comment true not working

### ISSUE THREAD

**Issue by ricardovanlaarhoven** [vebr/jest-lcov-reporter#23]
```
- name: report coverage based on jest
        uses: vebr/jest-lcov-reporter@v0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          update-comment: true
```
I've changed update-comment a while ago from false into true and the comments even from new PR's are still not updated.

Perhaps this is the same (but opposite) issue as #21
